In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("data/raw/wingspan-20260128.xlsx")
df

,Common name,Scientific name,Set,Color,Power text,Predator,Flocking,Bonus card,Victory points,Nest type,...,Nest Box Builder,Omnivore Expert,Passerine Specialist,Platform Builder,Prairie Manager,Rodentologist,Small Clutch Specialist,Viticulturalist,Wetland Scientist,Wildlife Gardener
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31%,0.16,35%,0.31,0.19,0.15,0.44,0.22,0.26,0.31
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.338048,0.165488,0.346535,0.314003,0.161245,0.137199,0.490806,0.23338,0.243281,0.340877
2,Abbott's Booby,Papasula abbotti,oceania,white,"Draw 3 bonus cards, then discard 2. You may di...",NaN,NaN,X,5.0,platform,...,NaN,NaN,NaN,X,NaN,NaN,X,NaN,X,NaN
3,Acadian Flycatcher,Empidonax virescens,promoUS,brown,Draw and discard 1 [card] from the deck. If it...,NaN,NaN,NaN,2.0,wild,...,X,NaN,X,X,NaN,NaN,X,NaN,NaN,X
4,Acorn Woodpecker,Melanerpes formicivorus,core,brown,"Gain 1 [seed] from the birdfeeder, if availabl...",NaN,NaN,NaN,5.0,cavity,...,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,Yellow-Headed Caracara,Daptrius chimachima,americas,pink,If there is an [invertebrate] or [rodent] in t...,X,NaN,NaN,4.0,platform,...,NaN,NaN,NaN,X,X,X,NaN,NaN,NaN,NaN
705,Yellow-Rumped Warbler,Setophaga coronata,core,brown,Tuck 1 [card] from your hand behind this bird....,NaN,X,NaN,1.0,bowl,...,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,X
706,Yellowhammer,Emberiza citrinella,european,teal,"If you used all 4 types of actions this round,...",NaN,NaN,NaN,2.0,ground,...,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,Yellowhead,Mohoua ochrocephala,promoNZ,yellow,"Reset the birdfeeder twice. Each time, cache a...",NaN,NaN,NaN,5.0,bowl,...,NaN,NaN,X,NaN,NaN,NaN,X,X,NaN,X
708,Zebra Dove,Geopelia striata,asia,brown,All players may discard 1 [seed] from their su...,NaN,NaN,NaN,4.0,platform,...,NaN,NaN,X,X,X,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,Common name,Scientific name,Set,Color,Power text,Predator,Flocking,Bonus card,Victory points,Nest type,Egg limit,Wingspan,Forest,Grassland,Wetland,Invertebrate,Seed,Fish,Fruit,Rodent,Nectar,Wild (food),/ (food cost),* (food cost),Total food cost,Beak direction,Swift Start,Automa ban,Flavor text,North America,Central America,South America,Europe,Asia,Africa,Oceania,Fan Art Pack?,Fan Art flavor text,Fan art beak direction,Anatomist,Cartographer,Historian,Photographer,Backyard Birder,Bird Bander,Bird Counter,Bird Feeder,Diet Specialist,Enclosure Builder,Endangered Species Protector,Falconer,Fishery Manager,Food Web Expert,Forester,Large Bird Specialist,Nest Box Builder,Omnivore Expert,Passerine Specialist,Platform Builder,Prairie Manager,Rodentologist,Small Clutch Specialist,Viticulturalist,Wetland Scientist,Wildlife Gardener
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.22,0.21,0.11,0.34,0.42,0.31,0.15,0.44,0.29,0.31,0.09,0.13,0.18,0.09,0.24,0.35,31%,0.16,35%,0.31,0.19,0.15,0.44,0.22,0.26,0.31
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.223479,0.270156,0.055163,0.325318,0.448373,0.34512,0.161245,0.408769,0.2843,0.369165,0.091938,0.125884,0.15983,0.123055,0.250354,0.366337,0.338048,0.165488,0.346535,0.314003,0.161245,0.137199,0.490806,0.23338,0.243281,0.340877
2,Abbott's Booby,Papasula abbotti,oceania,white,"Draw 3 bonus cards, then discard 2. You may di...",NaN,NaN,X,5.0,platform,1.0,190,NaN,NaN,X,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,L,NaN,NaN,"This large, endangered seabird lives only on C...",NaN,NaN,NaN,NaN,NaN,NaN,X,X,Kasey cut this Abbott's Booby from constructio...,R,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,NaN,X,NaN,NaN,NaN,X,NaN,NaN,X,NaN,X,NaN
3,Acadian Flycatcher,Empidonax virescens,promoUS,brown,Draw and discard 1 [card] from the deck. If it...,NaN,NaN,NaN,2.0,wild,2.0,23,X,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,L,NaN,NaN,The exceptionally maneuverable Acadian flycatc...,X,X,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,X,X,NaN,X,NaN,X,X,NaN,NaN,X,NaN,NaN,X
4,Acorn Woodpecker,Melanerpes formicivorus,core,brown,"Gain 1 [seed] from the birdfeeder, if availabl...",NaN,NaN,NaN,5.0,cavity,4.0,46,X,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,R,NaN,NaN,"In a single dead tree, these birds may drill a...",X,X,NaN,NaN,NaN,NaN,NaN,X,"Using watercolor paint, Tiffany Michael illust...",R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,X,NaN,NaN,NaN,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head(15).to_csv("data/raw/wingspan_head15.csv", index=False)